# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Distributional distance computation for discrete varialbles '
#' @param X1 The first serie of integers
#' @param X2 The second serie of integers
#' @return The distributional disancte between X1 and X2 using a $2^-i$ ponderation
#' @examples 
#' X1 <- as.integer(c(12, 13, 14, 12, 13, 16, 12, 13, 15, 12, 13, 16, 11, 13, 15, 12, 13, 16))
#' X2 <- as.integer(c(12, 13, 14, 19, 13, 16, 12, 13, 15, 12, 13, 16, 11, 13, 15, 12, 13, 16))
#' distributionalDistDiscrete(X1, X2)
#' @export
distributionalDistDiscrete <- function(X1, X2) {
    .Call(`_distributionalDist_distributionalDistDiscrete`, X1, X2)
}

#' Distributional distance computation for continuous varialbles '
#' @param X1 The first serie of integers
#' @param X2 The second serie of integers
#' @param nM a vector of length 2 with the initial values for the first discretization. If missing will be filled with min and max values
#' @return The distributional disancte between X1 and X2 using a $2^-i$ ponderation
#' @examples 
#' X1 <- c(-1,2.6,-4,5.5,7,1.8 );
#' X2 <- c(-0.5,2.6,-4,5.5,9,1.81);
#' distributionalDistContinuous(X1, X2)
#' @export
distributionalDistContinuous <- function(X1, X2, nM) {
    if (missing(nM)){
        X = c(X1, X2)
        nM = c(min(X), max(X))
    }
    .Call(`_distributionalDist_distributionalDistContinuous`, X1, X2, nM)
}

